services:
  hugo:
    image: ghcr.io/gohugoio/hugo:latest
    # The command now installs node modules before launching the server
    command: sh -c "npm install && hugo server --bind 0.0.0.0 --watch"
    volumes:
      - .:/project
    ports:
      - "1313:1313"